name: Build

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pip install .
        pylint `find .| grep .py$ | xargs`
    - name: Install ROS
      uses: suddrey-qut/setup-ros@master
      with:
        required-ros-distributions: noetic
    - name: ROSDep Install
      run: |
        source /opt/ros/noetic/setup.bash && rosdep update
        source /opt/ros/noetic/setup.bash && rosdep install --from-paths . --ignore-src -r -y
    - name: Test with pytest
      run: |
        pip install pytest-timeout pytest-cov
        source /opt/ros/noetic/setup.bash && PYTHONPATH=$PYTHONPATH:/usr/lib/$(python --version | sed 's/Python \([0-9]\.[0-9]\).*/python\1/')/dist-packages:/usr/lib/$(python --version | sed 's/Python \([0-9]\)\.[0-9].*/python\1/')/dist-packages pytest --cov=manipulation_driver --cov-report xml:coverage.xml --timeout=30 --timeout_method thread -s
    - name: upload coverage to Codecov
      uses: codecov/codecov-action@master
      with:
        file: ./coverage.xml
        
