name: 'Publish Armer release'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            python-version: 3.8
            ros-distro: noetic
    steps:
      - name: Checkout site code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ROS
        uses: suddrey-qut/setup-ros@master
        with:
          required-ros-distributions: ${{ matrix.ros-distro }}
      - name: ROSDep Install
        run: |
          source /opt/ros/${{ matrix.ros-distro }}/setup.bash && rosdep update
          source /opt/ros/${{ matrix.ros-distro }}/setup.bash && rosdep install --from-paths . --ignore-src -r -y
      - name: Install dependencies
        run: |
          echo "TODO"
          python3 -m pip install --upgrade pip
          sudo apt install python3-rospy
          sudo apt install python3-rospkg
          sudo apt install python3-sphinx
          python3 -m pip install roboticstoolbox-python
          python3 -m pip install sphinx-markdown-tables
          python3 -m pip install sphinx-rtd-theme
          python3 -m pip install recommonmark
          python3 -m pip install sphinxcontrib-openapi
      - name: Build
        run: |
          echo "TODO"
      - name: Push result to gh_pages branch
        run: |
          pushd docs
          source /opt/ros/${{ matrix.ros-distro }}/setup.bash && make html 
          # source /opt/ros/${{ matrix.ros-distro }}/setup.bash && PYTHONPATH=$PYTHONPATH:/usr/lib/$(python --version | sed 's/Python \([0-9]\.[0-9]\).*/python\1/')/dist-packages:/usr/lib/$(python --version | sed 's/Python \([0-9]\)\.[0-9].*/python\1/')/dist-packages make html 
          popd 
          cp -r docs/build/ ../
          git fetch --all
          git checkout -f gh_pages
          git reset --hard build_root
          git clean -d -x -f
          cp -r ../build/html/* .
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generated from contents of master commit: $(git rev-parse --short "$GITHUB_SHA")"
          git push -f
