name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install ROS
      uses: ros-tooling/setup-ros@0.1.1
      with:
        required-ros-distributions: melodic
    - name: Analysing the code with pylint
      run: |
        pip install .
        pip install pytest-timeout
        run: "source /opt/ros/melodic/setup.bash && pytest --timeout=30 --timeout_method thread -s"
